//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.CodeBuilder.Request
{
    /// <summary>
       ///
       /// </summary>

    public class AddOrUpdateUserBuilderLogReq
    {
        /// <summary>
       ///
       /// </summary>
       public int Id { get; set; }

       /// <summary>
       ///是否删除
       /// </summary>
       public bool Flag { get; set; }

       /// <summary>
       ///
       /// </summary>
       public DateTime AddTime { get; set; }

       /// <summary>
       ///最后更新时间
       /// </summary>
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///
       /// </summary>
       public string AdminRemark { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       public string Remark { get; set; }

       /// <summary>
       ///
       /// </summary>
       public string AdditionNote { get; set; }

       /// <summary>
       ///租户Id
       /// </summary>
       public int TenantId { get; set; }

       /// <summary>
       ///用户Id
       /// </summary>
       public string UserId { get; set; }

       /// <summary>
       ///表名
       /// </summary>
       public string TableName { get; set; }

       /// <summary>
       ///模块名称
       /// </summary>
       public string ModuleName { get; set; }

       /// <summary>
       ///存放路径
       /// </summary>
       public string Path { get; set; }

       /// <summary>
       ///发送次数
       /// </summary>
       public int? Count { get; set; }

       
    }
}