//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:feng yuan
//------------------------------------------------------------------------------
using Senparc.Ncf.Core.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using Senparc.Xncf.MaQueKeTang.Request;

namespace Senparc.Xncf.MaQueKeTang
{
    /// <summary>
///实体类
/// </summary>

    [Table(Register.DATABASE_PREFIX + nameof(CourseUser))]//必须添加前缀，防止全系统中发生冲突
    [Serializable]
    public class CourseUser : EntityBase<int>
    {
    public CourseUser()
    {
           this.AccountId=0;
       this.CourseId=0;
       this.charge=0;
       this.Flag=false;
       this.AddTime=DateTime.Now;;
       this.LastUpdateTime=DateTime.Now;;
       this.AdminRemark="";
       this.Remark="";
       this.TenantId=0;

    }
    public CourseUser(AddOrUpdateCourseUserReq req)
    {
           this.AccountId= req.AccountId;
       this.CourseId= req.CourseId;
       this.charge= req.charge;
       this.Flag= req.Flag;
       this.AddTime= req.AddTime;
       this.LastUpdateTime= req.LastUpdateTime;
       this.AdminRemark= req.AdminRemark;
       this.Remark= req.Remark;
       this.TenantId= req.TenantId;

    }

    /// <summary>
       ///用户Id
       /// </summary>
       [Description("用户Id")]
       public int AccountId { get; set; }

       /// <summary>
       ///课程Id
       /// </summary>
       [Description("课程Id")]
       public int CourseId { get; set; }

       /// <summary>
       ///收费
       /// </summary>
       [Description("收费")]
       public int charge { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       [Description("删除状态")]
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       [Description("添加时间")]
       public DateTime AddTime { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       [Description("最后修改时间")]
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       [Description("备注")]
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       [Description("说明")]
       public string Remark { get; set; }

       /// <summary>
       ///租户Id
       /// </summary>
       [Description("租户Id")]
       public int TenantId { get; set; }

       
    }
    }
