//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:feng yuan
//------------------------------------------------------------------------------
using Senparc.Ncf.Core.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using Senparc.Xncf.MaQueKeTang.Request;

namespace Senparc.Xncf.MaQueKeTang
{
    /// <summary>
///实体类
/// </summary>

    [Table(Register.DATABASE_PREFIX + nameof(CourseUserRecord))]//必须添加前缀，防止全系统中发生冲突
    [Serializable]
    public class CourseUserRecord : EntityBase<int>
    {
    public CourseUserRecord()
    {
           this.CourseId=0;
       this.AccountId=0;
       this.deleted_at=DateTime.Now;;
       this.is_watched=0;
       this.watched_at=DateTime.Now;;
       this.progress=0;
       this.Flag=false;
       this.AddTime=DateTime.Now;;
       this.LastUpdateTime=DateTime.Now;;
       this.AdminRemark="";
       this.Remark="";
       this.TenantId=0;

    }
    public CourseUserRecord(AddOrUpdateCourseUserRecordReq req)
    {
           this.CourseId= req.CourseId;
       this.AccountId= req.AccountId;
       this.deleted_at= req.deleted_at;
       this.is_watched= req.is_watched;
       this.watched_at= req.watched_at;
       this.progress= req.progress;
       this.Flag= req.Flag;
       this.AddTime= req.AddTime;
       this.LastUpdateTime= req.LastUpdateTime;
       this.AdminRemark= req.AdminRemark;
       this.Remark= req.Remark;
       this.TenantId= req.TenantId;

    }

    /// <summary>
       ///课程Id
       /// </summary>
       [Description("课程Id")]
       public int CourseId { get; set; }

       /// <summary>
       ///用户Id
       /// </summary>
       [Description("用户Id")]
       public int AccountId { get; set; }

       /// <summary>
       ///删除时间
       /// </summary>
       [Description("删除时间")]
       public DateTime? deleted_at { get; set; }

       /// <summary>
       ///看完,0否,1是
       /// </summary>
       [Description("看完,0否,1是")]
       public byte is_watched { get; set; }

       /// <summary>
       ///观看时间
       /// </summary>
       [Description("观看时间")]
       public DateTime? watched_at { get; set; }

       /// <summary>
       ///进度
       /// </summary>
       [Description("进度")]
       public byte progress { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       [Description("删除状态")]
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       [Description("添加时间")]
       public DateTime AddTime { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       [Description("最后修改时间")]
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       [Description("备注")]
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       [Description("说明")]
       public string Remark { get; set; }

       /// <summary>
       ///租户Id
       /// </summary>
       [Description("租户Id")]
       public int TenantId { get; set; }

       
    }
    }
