//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

namespace Senparc.Xncf.CodeBuilder.Request
{
    /// <summary>
	/// 代码生成器的表信息
	/// </summary>
    public class CreateBusiReq 
    {
        /// <summary>
        /// 代码生成模版Id
        /// </summary>
        public int Id { get; set; }
    }
}