//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:feng yuan
//------------------------------------------------------------------------------
using Senparc.Ncf.Core.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.MaQueKeTang.Models.DatabaseModel.Dto
{
    public class CourseDto : DtoBase
    {
        public CourseDto() { }

		/// <summary>
       ///用户Id
       /// </summary>
       [Description("用户Id")]
       public int AccountId { get; set; }

       /// <summary>
       ///名
       /// </summary>
       [Description("名")]
       public string title { get; set; }

       /// <summary>
       ///slug
       /// </summary>
       [Description("slug")]
       public string slug { get; set; }

       /// <summary>
       ///封面
       /// </summary>
       [Description("封面")]
       public string thumb { get; set; }

       /// <summary>
       ///收费
       /// </summary>
       [Description("收费")]
       public int charge { get; set; }

       /// <summary>
       ///简短介绍
       /// </summary>
       [Description("简短介绍")]
       public string short_description { get; set; }

       /// <summary>
       ///简介原始内容
       /// </summary>
       [Description("简介原始内容")]
       public string original_desc { get; set; }

       /// <summary>
       ///简介渲染后的内容
       /// </summary>
       [Description("简介渲染后的内容")]
       public string render_desc { get; set; }

       /// <summary>
       ///SEO关键字
       /// </summary>
       [Description("SEO关键字")]
       public string seo_keywords { get; set; }

       /// <summary>
       ///SEO描述
       /// </summary>
       [Description("SEO描述")]
       public string seo_description { get; set; }

       /// <summary>
       ///上线时间
       /// </summary>
       [Description("上线时间")]
       public DateTime? published_at { get; set; }

       /// <summary>
       ///1显示,-1隐藏
       /// </summary>
       [Description("1显示,-1隐藏")]
       public byte is_show { get; set; }

       /// <summary>
       ///分类id
       /// </summary>
       [Description("分类id")]
       public int category_id { get; set; }

       /// <summary>
       ///推荐,0否,1是
       /// </summary>
       [Description("推荐,0否,1是")]
       public byte is_rec { get; set; }

       /// <summary>
       ///学习人数
       /// </summary>
       [Description("学习人数")]
       public int user_count { get; set; }

       /// <summary>
       ///免费,0否,1是
       /// </summary>
       [Description("免费,0否,1是")]
       public byte is_free { get; set; }

       /// <summary>
       ///0关闭评论,1所有人,2仅购买
       /// </summary>
       [Description("0关闭评论,1所有人,2仅购买")]
       public byte comment_status { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       [Description("删除状态")]
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       [Description("添加时间")]
       public DateTime AddTime { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       [Description("最后修改时间")]
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       [Description("备注")]
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       [Description("说明")]
       public string Remark { get; set; }

       /// <summary>
       ///租户Id
       /// </summary>
       [Description("租户Id")]
       public int TenantId { get; set; }

       /// <summary>
       ///删除时间
       /// </summary>
       [Description("删除时间")]
       public DateTime? deleted_at { get; set; }

       

    }
}

