//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:feng yuan
//------------------------------------------------------------------------------
using Senparc.Ncf.Core.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.MaQueKeTang.Models.DatabaseModel.Dto
{
    public class CourseCategoryDto : DtoBase
    {
        public CourseCategoryDto() { }

		/// <summary>
       ///分类名
       /// </summary>
       [Description("分类名")]
       public string name { get; set; }

       /// <summary>
       ///父id
       /// </summary>
       [Description("父id")]
       public int parent_id { get; set; }

       /// <summary>
       ///父级名称
       /// </summary>
       [Description("父级名称")]
       public string parent_name { get; set; }

       /// <summary>
       ///是否显示,1显示,0不显示
       /// </summary>
       [Description("是否显示,1显示,0不显示")]
       public byte is_show { get; set; }

       /// <summary>
       ///升序
       /// </summary>
       [Description("升序")]
       public int sort { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       [Description("删除状态")]
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       [Description("添加时间")]
       public DateTime AddTime { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       [Description("最后修改时间")]
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       [Description("备注")]
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       [Description("说明")]
       public string Remark { get; set; }

       /// <summary>
       ///租户Id
       /// </summary>
       [Description("租户Id")]
       public int TenantId { get; set; }

       /// <summary>
       ///删除时间
       /// </summary>
       [Description("删除时间")]
       public DateTime? deleted_at { get; set; }

       

    }
}

