//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:feng yuan
//------------------------------------------------------------------------------
using Senparc.Ncf.Core.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.MaQueKeTang.Models.DatabaseModel.Dto
{
    public class VideoUserCommentDto : DtoBase
    {
        public VideoUserCommentDto() { }

		/// <summary>
       ///用户ID
       /// </summary>
       [Description("用户ID")]
       public int UserId { get; set; }

       /// <summary>
       ///视频ID
       /// </summary>
       [Description("视频ID")]
       public int VideoId { get; set; }

       /// <summary>
       ///原始内容
       /// </summary>
       [Description("原始内容")]
       public string OriginalContent { get; set; }

       /// <summary>
       ///渲染后的内容
       /// </summary>
       [Description("渲染后的内容")]
       public string RenderContent { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       [Description("删除状态")]
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       [Description("添加时间")]
       public DateTime AddTime { get; set; }

       /// <summary>
       ///添加者ID
       /// </summary>
       [Description("添加者ID")]
       public int? AddUserId { get; set; }

       /// <summary>
       ///添加者姓名
       /// </summary>
       [Description("添加者姓名")]
       public string AddUserName { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       [Description("最后修改时间")]
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///更新者ID
       /// </summary>
       [Description("更新者ID")]
       public int? UpdateUserId { get; set; }

       /// <summary>
       ///更新者姓名
       /// </summary>
       [Description("更新者姓名")]
       public string UpdateUserName { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       [Description("备注")]
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       [Description("说明")]
       public string Remark { get; set; }

       /// <summary>
       ///租户ID
       /// </summary>
       [Description("租户ID")]
       public int TenantId { get; set; }

       /// <summary>
       ///删除时间
       /// </summary>
       [Description("删除时间")]
       public DateTime? deleted_at { get; set; }

       

    }
}

