//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:feng yuan
//------------------------------------------------------------------------------
using Senparc.Ncf.Core.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.MaQueKeTang.Models.DatabaseModel.Dto
{
    public class VideoUserWatchRecordDto : DtoBase
    {
        public VideoUserWatchRecordDto() { }

		/// <summary>
       ///用户ID
       /// </summary>
       [Description("用户ID")]
       public int UserId { get; set; }

       /// <summary>
       ///课程ID
       /// </summary>
       [Description("课程ID")]
       public int CourseId { get; set; }

       /// <summary>
       ///视频ID
       /// </summary>
       [Description("视频ID")]
       public int VideoId { get; set; }

       /// <summary>
       ///已观看秒数
       /// </summary>
       [Description("已观看秒数")]
       public int WatchSeconds { get; set; }

       /// <summary>
       ///看完时间
       /// </summary>
       [Description("看完时间")]
       public DateTime? WatchedAt { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       [Description("删除状态")]
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       [Description("添加时间")]
       public DateTime AddTime { get; set; }

       /// <summary>
       ///添加者ID
       /// </summary>
       [Description("添加者ID")]
       public int? AddUserId { get; set; }

       /// <summary>
       ///添加者姓名
       /// </summary>
       [Description("添加者姓名")]
       public string AddUserName { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       [Description("最后修改时间")]
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///更新者ID
       /// </summary>
       [Description("更新者ID")]
       public int? UpdateUserId { get; set; }

       /// <summary>
       ///更新者姓名
       /// </summary>
       [Description("更新者姓名")]
       public string UpdateUserName { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       [Description("备注")]
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       [Description("说明")]
       public string Remark { get; set; }

       /// <summary>
       ///租户Id
       /// </summary>
       [Description("租户Id")]
       public int TenantId { get; set; }

       /// <summary>
       ///删除时间
       /// </summary>
       [Description("删除时间")]
       public DateTime? deleted_at { get; set; }

       

    }
}

