
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SenparcConf.Xncf.WechatBot.Models;

namespace SenparcConf.Xncf.WechatBot.Migrations.Migrations.Sqlite
{
    [DbContext(typeof(WechatBotSenparcEntities))]
    [Migration("20201226143133_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");
#pragma warning restore 612, 618
        }
    }
}
