//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.MaQueKeTang.Request
{
    /// <summary>
       ///
       /// </summary>

    public class AddOrUpdateCourseCategoryReq
    {
        /// <summary>
       ///分类名
       /// </summary>
       public string name { get; set; }

       /// <summary>
       ///父id
       /// </summary>
       public int parent_id { get; set; }

       /// <summary>
       ///父级名称
       /// </summary>
       public string parent_name { get; set; }

       /// <summary>
       ///是否显示,1显示,0不显示
       /// </summary>
       public byte is_show { get; set; }

       /// <summary>
       ///升序
       /// </summary>
       public int sort { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       public string Remark { get; set; }
       /// <summary>
       ///Id
       /// </summary>
       public int Id { get; set; }

       
    }
}