//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Senparc.Xncf.MaQueKeTang.Request
{
    /// <summary>
       ///
       /// </summary>

    public class AddOrUpdateVideoUserCommentReq
    {
        /// <summary>
       ///ID
       /// </summary>
       public int Id { get; set; }

       /// <summary>
       ///用户ID
       /// </summary>
       public int UserId { get; set; }

       /// <summary>
       ///视频ID
       /// </summary>
       public int VideoId { get; set; }

       /// <summary>
       ///原始内容
       /// </summary>
       public string OriginalContent { get; set; }

       /// <summary>
       ///渲染后的内容
       /// </summary>
       public string RenderContent { get; set; }

       /// <summary>
       ///删除状态
       /// </summary>
       public bool Flag { get; set; }

       /// <summary>
       ///添加时间
       /// </summary>
       public DateTime AddTime { get; set; }

       /// <summary>
       ///添加者ID
       /// </summary>
       public int? AddUserId { get; set; }

       /// <summary>
       ///添加者姓名
       /// </summary>
       public string AddUserName { get; set; }

       /// <summary>
       ///最后修改时间
       /// </summary>
       public DateTime LastUpdateTime { get; set; }

       /// <summary>
       ///更新者ID
       /// </summary>
       public int? UpdateUserId { get; set; }

       /// <summary>
       ///更新者姓名
       /// </summary>
       public string UpdateUserName { get; set; }

       /// <summary>
       ///备注
       /// </summary>
       public string AdminRemark { get; set; }

       /// <summary>
       ///说明
       /// </summary>
       public string Remark { get; set; }

       /// <summary>
       ///租户ID
       /// </summary>
       public int TenantId { get; set; }

       /// <summary>
       ///删除时间
       /// </summary>
       public DateTime? deleted_at { get; set; }

       
    }
}